{
 "title": "Basic \"Over Time\"",
 "time": { "from": "2024-08-31T13:03:22.029Z", "to": "2024-08-31T13:19:15.007Z" },
 "panels": [
  {
   "title": "Temperature over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, temperature from smisk.data_recordings;"
    }
   ]
  },
  {
   "title": "Humidity over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, (humidity * 100) as humidity from smisk.data_recordings;"
    }
   ]
  },
  {
   "title": "Air Quality Index over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, air_quality_index from smisk.data_recordings;"
    }
   ]
  },
  {
   "title": "CO2 Levels over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, co2_levels from smisk.data_recordings;"
    }
   ]
  },
  {
   "title": "Light Intensity over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "candela" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, light_intensity from smisk.data_recordings;"
    }
   ]
  },
  {
   "title": "Occupancy over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, occupancy FROM smisk.data_recordings"
    }
   ]
  }
 ]
}