FROM grafana/grafana:11.2.0

# Set Grafana admin username and password
ENV GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
ENV GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

# Add your data source configuration
COPY datasource.yaml /etc/grafana/provisioning/datasources/datasource.yaml

# Add your dashboard configuration
COPY dashboard.json /var/lib/grafana/dashboards/dashboard.json

# Add a custom dashboard provider to load your dashboard
COPY custom-dashboard.yaml /etc/grafana/provisioning/dashboards/custom-dashboard.yaml

EXPOSE 3000