version: '3.8'  # Specify the version of docker-compose file format

services:
  postgres:
    container_name: lrm-postgres
    hostname: lrm-postgres
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile  # Capitalized "Dockerfile" for convention
    networks:
      - grafana-network
      - collector-network
    ports:
      - "5432:5432"  # Added quotes for consistency in port mapping
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  data-collector:
    container_name: lrm-data-collector
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: ./data-collector
      dockerfile: Dockerfile
    networks:
      - collector-network
    environment:
      DATABASE_HOST: lrm-postgres
      DATABASE_PORT: "5432"
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data-collector-data:/usr/src/app

  grafana:
    container_name: lrm-grafana
    hostname: lrm-grafana
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: ./grafana
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    networks:
      - grafana-network
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  collector-network:
    driver: bridge
  grafana-network:
    driver: bridge

volumes:
  data-collector-data:
  postgres-data:
  grafana-data:
